services:
 
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}"
    volumes: 
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
